#!/bin/bash
#SBATCH --partition=luna-short
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --job-name=metrics_bbdmtopconfigs
#SBATCH --output=metricstopconfigs%A.out
#SBATCH --mem=8G
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:a100:1

set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/evaluation/PSNR_MAE_SSIM2.py \

  

 