#!/bin/bash
#SBATCH --partition=luna-short
#SBATCH --time=4:00:00
#SBATCH --nodes=1
#SBATCH --job-name=processs_input_val
#SBATCH --output=my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/processs_input_val%A.out
#SBATCH --mem=8G
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:4g.40gb:1

set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/preprocessing/train_test_val_splits_input.py \

  


