#!/bin/bash
#SBATCH --partition=luna-short
#SBATCH --time=3:00:00
#SBATCH --nodes=1
#SBATCH --job-name=nii_to_slice
#SBATCH --output=my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/nii_to_slice_%A.out
#SBATCH --mem=40G
#SBATCH --cpus-per-task=6


set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/raw_nii_to_slicescopy.py \



