#!/bin/bash
#SBATCH --partition=luna-long
#SBATCH --time=2:00:00
#SBATCH --nodes=1
#SBATCH --job-name=storedatabssfp
#SBATCH --output=my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/storedatabssfp%A.out
#SBATCH --mem=8G
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:a100:1

set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/doris_utils/process_bssfp.py \

  


