#!/bin/bash
#SBATCH --partition=luna-long
#SBATCH --time=7-00:00:00
#SBATCH --nodes=1
#SBATCH --job-name=topconfigs2_predict
#SBATCH --output=topconfigs_predict%A.out
#SBATCH --mem=80G
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:a100:1

set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/main.py \
    --config configs/Template_BBDM_topconfigs.yaml \
    --sample_to_eval \
    --gpu_ids 0 \
    --resume_model results/BBDM_topconfigs2/BrownianBridge/checkpoint/top_model_epoch_10.pth


