#!/bin/bash
#SBATCH --partition=luna-long
#SBATCH --time=48:00:00
#SBATCH --nodes=1
#SBATCH --job-name=Unet_instnorm_attention_train
#SBATCH --output=Unet_instnorm_attention/outputfiles/train_%A.out
#SBATCH --mem=80G
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:4g.40gb:1


set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/Unet_instnorm_attention/main.py \
    --epochs 10 \
    --batch_size 1 \
    --learning_rate 0.001 \
    --device cuda \
    --config config.yaml

