base_dir: 'data/slices_n98_s320x320_z88' #'data/testdata' # 'data/slices_n98_s320x320_z88'
mode:
  train: 'train'
  val: 'val'
  test: 'test'

batch_size:
  train: 16
  val: 16
  test: 1

epochs: 10 #1
learning_rate: 0.0001 #Learning rate adjusted # make not fixed?
architecture: 'Unetmultiinput1_dropout'
model_name: '10_epoch'

device: 'auto'  # 'auto', 'cuda', or 'cpu'

