#!/bin/bash
#SBATCH --partition=luna-long
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --job-name=multiunet2_predict
#SBATCH --output=Unetmultiinput2/outputfiles/predict_%A.out
#SBATCH --mem=8G
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:4g.40gb:1


set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/Unetmultiinput2/main.py \
    --device cuda \
    --mode predict \
    --model_path Unetmultiinput2/results/checkpoints/model_epoch_3.pth \
    --output_dir Unetmultiinput2/results/predictions/test1



