base_dir: 'data/testdata' # 'data/slices_n98_s320x320_z88'
mode:
  train: 'train'
  val: 'val'
  test: 'test'

batch_size:
  train: 16
  val: 16
  test: 1

epochs: 10
learning_rate: 0.001
architecture: 'Unetmultiinput1'
model_name: 'model_epoch'

device: 'auto'  # 'auto', 'cuda', or 'cpu'
