#!/bin/bash
#SBATCH --partition=luna-long
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --job-name=multiunet1
#SBATCH --output=Unetmultiinput1/outputfiles/UnetMulti1_%A.out
#SBATCH --mem=8G
#SBATCH --cpus-per-task=6


set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/Unetmultiinput1/main.py \
    --epochs 10 \
    --batch_size 16 \
    --learning_rate 0.001 \
    --device cuda \
    --config config.yaml

