#!/bin/bash
#SBATCH --partition=luna-long
#SBATCH --time=12:00:00
#SBATCH --nodes=1
#SBATCH --job-name=Unetbaseline_predict
#SBATCH --output=Unetbaseline/outputfiles/predict_%A.out
#SBATCH --mem=8G
#SBATCH --cpus-per-task=6
#SBATCH --gres=gpu:4g.40gb:1


set -eu

source $HOME/my-scratch/env/bin/activate

srun python $HOME/my-rdisk/r-divi/RNG/Projects/stages/Pim/Doris/BBDM_Thesis/Unetbaseline/main.py \
    --device cuda \
    --mode predict \
    --model_path Unetbaseline/results/checkpoints/10_epoch/model_9.pth \
    --output_dir Unetbaseline/results/predictions/10_epoch



