base_dir: 'data/slices_n98_s320x320_z88' #'data/testdata' 
mode:
  train: 'train'
  val: 'val'
  test: 'test'

batch_size:
  train: 16
  val: 16
  test: 1

epochs: 10 #1
learning_rate: 0.001
architecture: 'Unetbaseline_dropout' 
model_name: '10_epoch'

device: 'auto'  # 'auto', 'cuda', or 'cpu'

# python3 singleunetlarge/main.py --epochs 1 --batch_size 16 --learning_rate 0.001 --device auto --config config.yaml
# python3 singleunetlarge/main.py --epochs 10 --batch_size 16 --learning_rate 0.001 --device cuda --config config.yaml
# python3 singleunetlarge/main.py --device cuda --mode predict --model_path Unetmultiinput1/results/checkpoints/test1/epoch_1.pth --output_dir Unetmultiinput1/results/predictions

